version: '3.8'

services:
  stock-prediction-app:
    build: .
    container_name: stock-prediction-app
    ports:
      - "8502:8502"
    volumes:
      # Mount local directories to persist data
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
