services:
  - type: web
    name: stock-prediction-app
    env: python
    plan: free
    buildCommand: |
      pip install uv
      uv sync
    startCommand: uv run streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: PYTHONPATH
        value: /opt/render/project/src
