[server]
# Server configuration
port = 8501
address = "0.0.0.0"
headless = true
enableXsrfProtection = false
maxUploadSize = 200

[browser]
# Browser settings
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# Dark theme configuration
primaryColor = "#00D4AA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
# Client-side settings
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Performance settings
magicEnabled = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d %(levelname)s: %(message)s"
